from datetime import datetime
from pathlib import Path

from docx import Document
from docx.opc.constants import RELATIONSHIP_TYPE
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import RGBColor


def add_hyperlink(paragraph, url: str, text: str) -> None:
    """
    Add a clickable link to the end of a paragraph.

    python-docx has no API for hyperlinks, so the run is
    wrapped in a <w:hyperlink> element that points to the URL.
    """

    relationship_id = paragraph.part.relate_to(
        url, RELATIONSHIP_TYPE.HYPERLINK, is_external=True
    )

    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), relationship_id)

    # Blue and underlined, like links typed into Word
    run = paragraph.add_run(text)
    run.font.color.rgb = RGBColor(0x05, 0x63, 0xC1)
    run.font.underline = True

    hyperlink.append(run._r)
    paragraph._p.append(hyperlink)


def create_job_report(results, output_path) -> str:
    """
    Save the report and return the path it was saved to.
    """

    document = Document()

    document.add_heading("AI Job Matching Report", level=1)

    document.add_paragraph("Generated by the Job Matching Agent")

    for index, result in enumerate(results, start=1):

        document.add_heading(f"{index}. {result['job_title']}", level=2)

        document.add_paragraph(f"Company: {result['company']}")

        document.add_paragraph(f"Location: {result['location']}")

        document.add_paragraph(f"Experience: {result['experience']}")

        link_paragraph = document.add_paragraph("Job link: ")

        if result["source_url"]:
            add_hyperlink(link_paragraph, result["source_url"], result["source_url"])
        else:
            link_paragraph.add_run("Not available")

        document.add_paragraph(f"Skill Match: {result['match_percentage']}%")

        if result["relevant_roles"]:
            document.add_paragraph(
                f"Similar roles in your PDF: {', '.join(result['relevant_roles'])}"
            )

        document.add_heading("Matched Skills", level=3)

        if result["matched_skills"]:

            for skill in result["matched_skills"]:
                document.add_paragraph(skill, style="List Bullet")

        else:
            document.add_paragraph("No matched skills identified.")

        document.add_heading("Missing Skills", level=3)

        if result["missing_skills"]:

            for skill in result["missing_skills"]:
                document.add_paragraph(skill, style="List Bullet")

        else:
            document.add_paragraph("No missing skills identified.")

        document.add_heading("AI Analysis", level=3)

        document.add_paragraph(result["analysis"])

    try:
        document.save(output_path)

    except PermissionError:
        # The previous report is still open in Word
        path = Path(output_path)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = str(path.with_name(f"{path.stem}_{timestamp}{path.suffix}"))

        document.save(output_path)

    return output_path
